# Generated by Django 4.2.7 on 2024-08-23 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_cat', models.PositiveIntegerField()),
                ('second_cat', models.PositiveIntegerField()),
                ('first_test', models.PositiveIntegerField()),
                ('second_test', models.PositiveIntegerField()),
                ('exam_score', models.PositiveIntegerField()),
                ('total_score', models.PositiveIntegerField(blank=True, null=True)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.PositiveIntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
