# Generated by Django 4.2.7 on 2024-04-24 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_initial'),
        ('exam', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='topics',
            field=models.ManyToManyField(to='teachers.topic'),
        ),
        migrations.AlterField(
            model_name='session',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.exam'),
        ),
    ]
