# Generated by Django 4.2.7 on 2024-04-24 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_question_topics_alter_session_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topics',
        ),
    ]
