# Generated by Django 4.2.7 on 2024-06-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_alter_exam_name_alter_question_question_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_exam',
        ),
        migrations.AddConstraint(
            model_name='exam',
            constraint=models.UniqueConstraint(condition=models.Q(('ready', True)), fields=('name', 'created'), name='unique_exam'),
        ),
    ]
