# Generated by Django 4.2.7 on 2024-06-10 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_remove_exam_unique_exam_exam_unique_exam'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='exam',
            name='unique_exam',
        ),
        migrations.AlterField(
            model_name='exam',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
