# Generated by Django 4.2.7 on 2024-08-25 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_academicyear_term_and_more'),
        ('exam', '0004_alter_studentresult_exam_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentresult',
            name='academic_year',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.academicyear'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='subject',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentresult',
            name='term',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='school.term'),
            preserve_default=False,
        ),
    ]
