# Generated by Django 4.2.7 on 2024-06-22 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_question_explaination'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='explaination',
            new_name='explanation',
        ),
    ]
