# Generated by Django 4.2.7 on 2024-04-19 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_teacher_email'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='Students',
        ),
    ]
