# Generated by Django 4.2.7 on 2024-04-19 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_student_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table=None,
        ),
    ]
