# Generated by Django 4.2.7 on 2024-05-04 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_student_request_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.FileField(upload_to='photo', verbose_name='Photo'),
        ),
    ]
