# Generated by Django 4.2.7 on 2024-08-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='level',
            field=models.ManyToManyField(related_name='subject', to='school.grade'),
        ),
    ]
