# Generated by Django 4.2.7 on 2024-08-24 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_alter_subject_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='level',
            new_name='grade',
        ),
    ]
