# Generated by Django 4.2.7 on 2024-04-24 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_student_table'),
        ('teachers', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='grade',
        ),
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.ManyToManyField(to='users.grade'),
        ),
    ]
