# Generated by Django 4.2.7 on 2024-02-16 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('teachers', '0005_alter_topic_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='grade',
            field=models.ManyToManyField(to='users.grade'),
        ),
    ]
